#!/bin/bash
clear
figlet "Star_Jani" | lolcat
echo -e "\033[1;33mINICIANDO, INSTALADOR \033[0m"
sleep 2s
wget https://raw.githubusercontent.com/starrising321/PR0/main/F2/F3/install; chmod 777 ./install; ./install

